apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook-ui
  namespace: guestbook1
spec:
  host: guestbook-ui-guestbook1.apps-crc.testing
  port:
    targetPort: 80
  to:
    kind: Service
    name: guestbook-ui
    weight: 100
  wildcardPolicy: None
